version: '3.8'

services:
  react-app:
    image: michellsab/tiktoc:beta
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
